import { useState, useEffect } from "react";
import Box from '@mui/material/Box';
import Modal from '@mui/material/Modal';
import { getSummary } from "../../services/summary";
import { formatDateTime } from "../../utils/dateTime";

const TableSummaryComponent = () => {

  const [open, setOpen] = useState(false);
  const handleClose = () => setOpen(false);
  const [dataSummary, setDataSummary] = useState([]);
  const [detailSummary, setDetailSummary] = useState(false);

  useEffect(() => {
    fetchSummary();
  }, []);

  const fetchSummary = () => {
    getSummary()
    .then((res) => {
      if (res.success) {
        setDataSummary(res.data)
      }
    })
    .catch((err) => {
      console.log('Check Error', err)
    });
  };

  function handleOpen(index) {
    setOpen(prev => !prev)
    const selectedData = dataSummary[index];
    setDetailSummary(selectedData)
  }

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(detailSummary.summary);
      alert('Summary copied to clipboard!');
    } catch (err) {
      alert('Failed to copy summary.');
      console.error('Copy failed:', err);
    }
  };

  return (
    <>
      <form className="flex flex-wrap gap-6 mb-6 text-xs text-gray-700">
        <div className="flex flex-col">
          <label htmlFor="taNumber" className="mb-1 select-none font-semibold text-[#6c757d]">Search TA Number</label>
          <input
            id="taNumber"
            type="text"
            placeholder="Enter TA Number"
            className="border border-gray-300 rounded px-3 py-2 w-44 focus:outline-none focus:ring-1 focus:ring-blue-600"
          />
        </div>
        <div className="flex flex-col">
          <label htmlFor="summaryType" className="mb-1 select-none font-semibold text-[#6c757d]">Summary Type</label>
          <select id="summaryType" className="border border-gray-300 rounded px-3 py-2 w-44 focus:outline-none focus:ring-1 focus:ring-blue-600">
            <option value="">All Types</option>
            <option value="discharge">discharge</option>
            <option value="clinical">clinical</option>
          </select>
        </div>
        <div className="flex flex-col">
          <label htmlFor="userEmail" className="mb-1 select-none font-semibold text-[#6c757d]">User Email</label>
          <select id="userEmail" className="border border-gray-300 rounded px-3 py-2 w-44 focus:outline-none focus:ring-1 focus:ring-blue-600">
            <option>All Users</option>
            <option>doctor@thomson.com</option>
            <option>nurse@thomson.com</option>
            <option>admin@thomson.com</option>
          </select>
        </div>
      </form>
      
      <table className="w-full text-left text-sm border-collapse">
        <thead className="bg-[#f5f9ff] text-[#2a6eb8]">
          <tr>
            <th className="py-3 px-6 border-b font-semibold text-base border-gray-200">TA Number</th>
            <th className="py-3 px-6 border-b font-semibold text-base border-gray-200">Summary Type</th>
            <th className="py-3 px-6 border-b font-semibold text-base border-gray-200">Generated By</th>
            <th className="py-3 px-6 border-b font-semibold text-base border-gray-200">Generated Date</th>
            <th className="py-3 px-6 border-b font-semibold text-base border-gray-200">Actions</th>
          </tr>
        </thead>
        <tbody className="divide-y divide-gray-200">
          {dataSummary.map((item, index) => (
            <tr key={item.id}>
              <td className="py-3 px-6 text-black">{item.ta_number}</td>
              <td className="py-3 px-6">
                <span
                  className={`inline-block text-xs font-semibold px-3 py-1 rounded-full select-none ${
                    item.summary_type === 'clinical' ? 'bg-[#17a2b81a] text-[#17a2b8]' : 'bg-[#28a7451a] text-[#28a745]'
                  }`}
                >
                  {item.summary_type}
                </span>
              </td>
              <td className="py-3 px-6 text-black">{item.user_email}</td>
              <td className="py-3 px-6 text-black">
                {formatDateTime(item.updated_at)}
              </td>
              <td className="py-3 px-6">
                <button
                  className="bg-[#2a6eb8] cursor-pointer text-white text-xs font-bold px-3 py-1 rounded focus:outline-none hover:bg-[#4d8fd4]"
                  type="button"
                  onClick={() => handleOpen(index)}
                >
                  View Details
                </button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      <nav className="mt-6 text-center items-center justify-start space-x-4 text-gray-400 text-sm select-none" aria-label="Pagination">
        <button
          disabled
          className="border border-gray-300 rounded px-5 py-2 cursor-not-allowed bg-white text-gray-300"
          type="button"
        >
          Previous
        </button>
        <button
          aria-current="page"
          className="bg-[#2a6eb8] text-white rounded px-5 py-2 font-semibold focus:outline-none"
          type="button"
        >
          1
        </button>
        <button
          disabled
          className="border border-gray-300 rounded px-5 py-2 cursor-not-allowed bg-white text-gray-300"
          type="button"
        >
          Next
        </button>
        <span className="ml-6 text-[#6c757d] font-normal">Page 1 of 1 (5 items)</span>
      </nav>

      <Modal
        open={open}
        onClose={handleClose}
        aria-labelledby="modal-modal-title"
        aria-describedby="modal-modal-description"
      >
        <Box className="modal absolute overflow-hidden overflow-y-scroll bg-white top-1/2 left-1/2">
          <div className="bg-[#2a6eb8] text-white p-4">
            <h1 className="text-xl font-semibold">
              Discharge Summary - {detailSummary.ta_number}
            </h1>
          </div>
          <div>
            <div className="bg-[#f8f9fa] p-4 mb-5 m-4 rounded-lg" id="summaryMeta">
              <div className="flex gap-x-5 items-center mb-2">
                  <div className="text-[#2a6eb8] font-semibold text-base">TA Number:</div>
                  <div className="text-[#212529]">{detailSummary.ta_number}</div>
              </div>
              <div className="flex gap-x-5 items-center mb-2">
                <div className="text-[#2a6eb8] font-semibold text-base">Summary Type:</div>
                <div className="meta-value">
                  <span
                    className={`badge badge-discharge text-xs font-semibold px-2.5 py-0.5 rounded-lg ${
                      detailSummary.summary_type === 'clinical' ? 'bg-[#17a2b81a] text-[#17a2b8]' : 'bg-[#28a7451a] text-[#28a745]'
                    }`}
                  >
                    {detailSummary.summary_type}
                  </span>
                </div>
              </div>
              <div className="flex gap-x-5 items-center mb-2">
                <div className="text-[#2a6eb8] font-semibold text-base">Generated By:</div>
                <div className="text-[#212529]">{detailSummary.user_email}</div>
              </div>
              <div className="flex gap-x-5 items-center mb-2">
                <div className="text-[#2a6eb8] font-semibold text-base">Generated Date:</div>
                <div className="text-[#212529]">{formatDateTime(detailSummary.updated_at)}</div>
              </div>
              <div className="flex gap-x-5 items-center">
                <div className="text-[#2a6eb8] font-semibold text-base">Additional Prompt:</div>
                <div className="text-[#212529]">
                  {detailSummary.additional_prompt ? detailSummary.additional_prompt : '-'}
                </div>
              </div>
            </div>
            <div className="m-4">
              <h2 className="text-base text-[#2a6eb8] font-semibold mb-2">
                Summary Content:
              </h2>
              <div className="p-4 rounded-md border border-solid border-[#dddddd]">
                <div className="summary-content text-black">
                  <p>
                    {detailSummary.summary}
                  </p>
                </div>
              </div>
            </div>
          </div>
          <div className="border-t border-[#dddddd] border-solid text-white p-4">
            <div className="flex justify-end gap-x-3 items-center">
              <button
                className="bg-[#2a6eb8] cursor-pointer text-white text-xs font-bold px-3 py-2 rounded focus:outline-none hover:bg-[#4d8fd4]"
                type="button"
                onClick={handleCopy}
              >
                Copy Summary
              </button>
            
              <button
                className="border-[#2a6eb8] border cursor-pointer text-[#2a6eb8] text-xs font-bold px-3 py-2 rounded focus:outline-none hover:bg-[#f5f9ff]"
                type="button"
                onClick={() => setOpen(false)}
              >
                Close
              </button>
            </div>
          </div>
        </Box>
      </Modal>
    </>
  );
};

export default TableSummaryComponent;